# permissions for end users to edit workspacemanifests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workspacemanifest-editor-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - workspacemanifests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - workspacemanifests/status
  verbs:
  - get
