# permissions for end users to edit samplesvcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: samplesvc-editor-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - samplesvcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - samplesvcs/status
  verbs:
  - get
