apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: core.appstudio.redhat.com
spec:
  latestResourceSchemas:
    - today.core.appstudio.redhat.com
  permissionClaims:
    - group: ""
      resource: "secrets"
    - group: ""
      resource: "configmaps"
    - group: ""
      resource: "namespaces"
